## Lambda functions

- The lambda expression is more compact
- We don't need to specify "def", "return" 
- The logic of the lambda function is seen at the place where we execute it

In [ ]:
power = lambda x,y: x**y
power(4,2)

16

In [ ]:
squared  = lambda x:x**2
squared(4)

16

In [ ]:
squared_lambda = lambda x: x**2

def squared_normal(x):
  return x**2

In [ ]:
squared_lambda(5)

25

In [ ]:
squared_normal(5)

25

In [ ]:
(lambda x: x**2)(3)

9

In [ ]:
(lambda x, y: x+y)(3, 4)

7

In [ ]:
def square(x):
    return x*x

def twoTimesF(f):
    return lambda x: f(f(x))

quad = twoTimesF(square)

In [ ]:
quad(2)

16

# Zip() function

- Takes in two or more sequences as inputs
- Allows you to iterate through all the sequences at the same time

In [ ]:
languages=['Java', 'Python', 'C']
versions=[14, 3, 11]

result = zip(languages, versions)

print(list(result))

[('Java', 14), ('Python', 3), ('C', 11)]

In [ ]:
# points scored by each of five players in game1
points_game1 = [50, 40, 60, 70, 80]

# points scored by each of five players in game2
points_game2 = [76, 81, 53, 92, 67]

# sequence where points differences will be saved
diffs = []

# iterate through points_game1 and points_game2 at the same time
for x, y in zip(points_game1, points_game2):
    # compute absolute difference in points between game1 and game2
    # add to diffs
    diffs.append(abs(x - y))
    
diffs

[26, 41, 7, 22, 13]

# map() function

- Takes in function and sequence as inputs
- Ex: map(function, list)
- Returns an iterator that applies the function to every item in the sequence

In [3]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')
project_dir = 'drive/MyDrive/COMPTECH/Data/W2-D3/'

grades = pd.read_csv(project_dir+'grades.csv')
grades.head(20)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

    exam  student_id  grade
0      1           1   86.0
1      1           2   65.0
2      1           3   70.0
3      1           4   98.0
4      1           5   89.0
5      1           6    NaN
6      1           7   75.0
7      1           8   56.0
8      1           9   90.0
9      1          10   81.0
10     2           1   79.0
11     2           2   60.0
12     2           3   78.0
13     2           4   75.0
14     2           5    NaN
15     2           6   80.0
16     2           7   87.0
17     2           8   82.0
18     2           9   95.0
19     2          10   96.0

In [10]:
grades.loc[grades['student_id'] == 1]

    exam  student_id  grade
0      1           1   86.0
10     2           1   79.0
20     3           1   78.0
30     4           1    NaN
40     5           1   90.0

In [13]:
grades.loc[grades['student_id'] == 3]

    exam  student_id  grade
2      1           3   70.0
12     2           3   78.0
22     3           3   87.0
32     4           3   81.0
42     5           3   91.0

In [5]:
def lowest_grade(student_id):
    
    """Find lowest grade across all exams for student with given student_id.
    Treat missing exam grades as zeros."""
    
    return grades.loc[grades['student_id'] == student_id]['grade'].fillna(0).min()

In [11]:
lowest_grade(1)

0.0

In [21]:
lowest_grade(9)

73.0

In [12]:
# test lowest_grade on student_id 1
assert lowest_grade(1) == 0.0, 'test failed'
print('test passed')

test passed

In [16]:
# # test lowest_grade on student_id 1
# assert lowest_grade(3) == 0.0, 'test failed'
# print('test passed')

In [18]:
# sequence containing all distinct student ids
student_ids = grades['student_id'].unique()
student_ids

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# apply lowest_grade to each student id
list(map(lowest_grade, student_ids))

[0.0, 0.0, 70.0, 0.0, 0.0, 0.0, 75.0, 56.0, 73.0, 75.0]

In [20]:
lowest_grade_per_student = list(map(lowest_grade, student_ids))

In [25]:
lowest_grade_per_student_id = list(zip(student_ids,lowest_grade_per_student))
lowest_grade_per_student_id

[(1, 0.0),
 (2, 0.0),
 (3, 70.0),
 (4, 0.0),
 (5, 0.0),
 (6, 0.0),
 (7, 75.0),
 (8, 56.0),
 (9, 73.0),
 (10, 75.0)]



---

In [ ]:
def CelsisusToFahrenheit(temp):
    return (temp * 9/5) + 32

def FahrenheitToCelsisus(temp):
    return (temp-32) * 5/9

In [ ]:
ctemps = [0, 12, 34, 100]
ftemps = [32, 65, 100, 212]

# Use regular functions to convert temps
print(list(map(FahrenheitToCelsisus, ftemps)))
print(list(map(CelsisusToFahrenheit, ctemps)))

[0.0, 18.333333333333332, 37.77777777777778, 100.0]
[32.0, 53.6, 93.2, 212.0]

In [ ]:
# Use lambdas to accomplish the same thing
print(list(map(lambda t: (t-32) * 5/9, ftemps)))
print(list(map(lambda t: (t * 9/5) + 32, ctemps)))

[0.0, 18.333333333333332, 37.77777777777778, 100.0]
[32.0, 53.6, 93.2, 212.0]

# filter() function

- Takes in two more sequences as inputs
- Allows you to iterate through all the sequences at the same time

In [ ]:
def mean_atleast_70(student_id):
    
    """Compute mean grade across all exams for student with given student_id.
    Treat missing exam grades as zeros.
    If mean grade is atleast 70, return True. Otherwise, return False."""
    
    mean_grade = grades.loc[grades['student_id'] == student_id]['grade'].fillna(0).mean()
    return mean_grade >= 70

In [ ]:
# test mean_grade on student_id 1
assert mean_atleast_70(1) == False, 'test failed'
print('test passed')

test passed

In [ ]:
# sequence containing all distinct student ids
student_ids = grades['student_id'].unique()
student_ids

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# list the student ids in which the mean exam grade is at least 70
# apply the function to all student ids and return only the list of student ids that meet the condition
list(filter(mean_atleast_70, student_ids))

[3, 5, 7, 8, 9, 10]